pipeline:
  name: aws-teaagrunt
  identifier: awsteaagrunt
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: infra
        identifier: infra
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerragruntPlan
                  name: TerragruntPlan_1
                  identifier: TerragruntPlan_1
                  spec:
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          type: Github
                          spec:
                            gitFetchType: Branch
                            connectorRef: account.Github_OAuth_1702454216196
                            repoName: terragrunt-aws-hos
                            branch: main
                            folderPath: .
                      moduleConfig:
                        terragruntRunType: RunModule
                        path: terragrunt-vsphere-harness-live/dev
                      secretManagerRef: harnessSecretManager
                      environmentVariables:
                        - name: JFROG_TOKEN
                          value: <+secrets.getValue("JFROG_TOKEN")>
                          type: String
                      exportTerragruntPlanJson: true
                    provisionerIdentifier: dev
                  timeout: 10m
              - step:
                  type: TerragruntApply
                  name: TerragruntApply_1
                  identifier: TerragruntApply_1
                  spec:
                    configuration:
                      type: InheritFromPlan
                      commandFlags:
                        - commandType: OUTPUT
                          flag: "-json >/tmp/output.json"
                    provisionerIdentifier: dev
                  timeout: 10m
        tags: {}
